# Two dimensional Array

In [1]:
import numpy as np

In [3]:
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim # Shows the dimension of array

2

In [6]:
A.shape # Indicates size in each dimension

(3, 3)

In [8]:
A.size # Indicates the length of array

9

In [10]:
A[1][0] # To fetch the element at 2nd row and 1st column

21

In [12]:
A[1,0] # Another way to fetch data

21

In [14]:
A[0:2,2] # Fetching the 3rd cloumn from 1st to 2nd row

array([13, 23])

### Vector Addition and Subtraction of arrays

In [19]:
#Addition
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

In [18]:
#Subtraction
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=X-Y
Z

array([[-1, -1],
       [-1, -1]])

### Scalar Multilication of numpy array

In [21]:
Z=2*Y
Z

array([[4, 2],
       [2, 4]])

### Multiplication of two arrays

In [22]:
Z=X*Y
Z

array([[2, 0],
       [0, 2]])

### Dot Product of two arrays

In [24]:
A=np.array([[0,1,1],[1,0,1]])
B=np.array([[1,1],[1,1],[-1,1]])
C=np.dot(A,B)
C

array([[0, 2],
       [0, 2]])